version: "2"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8010:8010'
  ui:
    build:
      dockerfile: Dockerfile.dev
      context: ./ui
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
  
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
