version: "2"

services:
  nginx:
    restart: always
    build: ./nginx
    image: nginx
    ports:
      - '8010:8010'
  ui:
    build: ./ui
    image: ui
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - network
  
  api:
    build: ./api
    image: api
    ports:
      - "80:80"
    volumes:
      - ./api:/api
    networks:
      - network

networks:
  network:
    driver: bridge
